import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Stage 2: Output types — what the generation agent must produce per page part
// ---------------------------------------------------------------------------

/** Article body output (metadata + MDX body content). */
export const ArticleBodyOutputSchema = z.object({
  metadata: z.object({
    title: z.string().min(1),
    description: z.string(),
    date: z.string(),
    category: z.string(),
  }),
  body: z.string().min(1),
});

/** A single CTA component as generated by the writer agent. */
export const CtaComponentOutputSchema = z.object({
  type: z.string().min(1),
  eyebrow: z.string().min(1),
  title: z.string().min(1),
  body: z.string().min(1),
  buttonText: z.string().min(1),
  href: z.string().optional(),
});

/** JSON-LD structured data output. */
export const JsonLdOutputSchema = z.object({
  schemaType: z.string().min(1),
  data: z.record(z.string(), z.unknown()),
});
